services:
  server:
    build: ./server
    container_name: synerprise_server
    command: gunicorn core.wsgi:application --bind 0.0.0.0:${SERVER_PORT}
    volumes:
      - ./server:/app
    ports:
      - "${SERVER_PORT}:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  client:
    build: ./client
    container_name: synerprise_client
    volumes:
      - ./client/public:/app/public
      - ./client/.env:/app/.env
    ports:
      - "${CLIENT_PORT}:3000"
    depends_on:
      - server

  synerprise-model:
    build: ./synerprise-model
    container_name: synerprise_model_service
    ports:
      - "${SYNERPRISE_MODEL_PORT}:9000"
    volumes:
      - ./synerprise-model:/app
    command: uvicorn main:app --host 0.0.0.0 --port ${SYNERPRISE_MODEL_PORT}
    restart: always
    depends_on:
      - redis
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: synerprise_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env

  redis:
    image: redis:6.2
    container_name: synerprise_redis
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env

volumes:
  pgdata:

